export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const DELETE_SELECTED_PRODUCT = "DELETE_SELECTED_PRODUCT";